apiVersion: v1
kind: Service
metadata:
    name: servico-aplicao-noticia
spec:
    type: LoadBalancer
    ports:
        - name: http
          port: 80
    selector: 
      name: aplicacao-noticia-pod    